// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Primary design header
//
// This header should be included by all source files instantiating the design.
// The class here is then constructed to instantiate the design.
// See the Verilator manual for examples.

#ifndef _Vdig_H_
#define _Vdig_H_

#include "verilated.h"
#include "Vdig__Inlines.h"
class Vdig__Syms;
class VerilatedVcd;

//----------

VL_MODULE(Vdig) {
  public:
    // CELLS
    // Public to allow access to /*verilator_public*/ items;
    // otherwise the application code can consider these internals.
    
    // PORTS
    // The application code writes and reads these signals to
    // propagate new values into/out from the Verilated model.
    VL_IN8(nres,0,0);
    VL_IN8(clk_cog,0,0);
    VL_IN8(clk_pll,0,0);
    VL_OUT8(cfg,7,0);
    VL_OUT8(cog_led,7,0);
    //char	__VpadToAlign5[3];
    VL_IN(pin_in,31,0);
    VL_OUT(pin_out,31,0);
    VL_OUT(pin_dir,31,0);
    
    // LOCAL SIGNALS
    // Internals; generally not touched by application code
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(dig__DOT__ena_bus,0,0);
    VL_SIG8(dig__DOT__bus_sel,7,0);
    VL_SIG8(dig__DOT__bus_r,7,0);
    VL_SIG8(dig__DOT__bus_e,7,0);
    VL_SIG8(dig__DOT__bus_w,7,0);
    //char	__VpadToAlign37[3];
    VL_SIG16(dig__DOT__bus_s,15,0);
    VL_SIG8(dig__DOT__bus_ack,7,0);
    VL_SIG8(dig__DOT__pll,7,0);
    VL_SIG8(dig__DOT__ptr_w,7,0);
    VL_SIG8(dig__DOT__cog_ena,7,0);
    VL_SIG8(dig__DOT__hub___DOT__rc,0,0);
    VL_SIG8(dig__DOT__hub___DOT__ec,0,0);
    VL_SIG8(dig__DOT__hub___DOT__wc,0,0);
    VL_SIG8(dig__DOT__hub___DOT__sc,1,0);
    VL_SIG8(dig__DOT__hub___DOT__mem_w,0,0);
    VL_SIG8(dig__DOT__hub___DOT__mem_wb,3,0);
    VL_SIG8(dig__DOT__hub___DOT__rd,0,0);
    VL_SIG8(dig__DOT__hub___DOT__ed,0,0);
    VL_SIG8(dig__DOT__hub___DOT__sd,1,0);
    VL_SIG8(dig__DOT__hub___DOT__ad,1,0);
    VL_SIG8(dig__DOT__hub___DOT__sys_q,2,0);
    VL_SIG8(dig__DOT__hub___DOT__sys_c,0,0);
    VL_SIG8(dig__DOT__hub___DOT__cog_e,7,0);
    VL_SIG8(dig__DOT__hub___DOT__lock_e,7,0);
    VL_SIG8(dig__DOT__hub___DOT__sys,0,0);
    VL_SIG8(dig__DOT__hub___DOT__enc,7,0);
    VL_SIG8(dig__DOT__hub___DOT__num,2,0);
    VL_SIG8(dig__DOT__hub___DOT__cog_start,0,0);
    VL_SIG8(dig__DOT__hub___DOT__lock_state,7,0);
    VL_SIG8(dig__DOT__hub___DOT__hub_mem___DOT__ram_q3,7,0);
    VL_SIG8(dig__DOT__hub___DOT__hub_mem___DOT__ram_q2,7,0);
    VL_SIG8(dig__DOT__hub___DOT__hub_mem___DOT__ram_q1,7,0);
    VL_SIG8(dig__DOT__hub___DOT__hub_mem___DOT__ram_q0,7,0);
    VL_SIG8(dig__DOT__hub___DOT__hub_mem___DOT__mem,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__run,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__c,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__z,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cond,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__alu_zo,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__wio,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__setphsa,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__setphsb,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__ram_ena,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__plla,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__pllb,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cancel,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__jumpx,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__match,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ctra__DOT__dly,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ctra__DOT__tba,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ctrb__DOT__dly,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ctrb__DOT__tba,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__cnts,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__cnt,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__new_set,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__new_cnt,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__cap,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__discrete,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__phase,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__baseband,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__colorphs,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__colormod,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__composite,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__broadcast,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_alu___DOT__add_sub,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_alu___DOT__add_cs,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__run,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__c,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__z,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cond,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__alu_zo,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__wio,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__setphsa,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__setphsb,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__ram_ena,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__plla,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__pllb,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cancel,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__jumpx,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__match,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ctra__DOT__dly,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ctra__DOT__tba,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ctrb__DOT__dly,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ctrb__DOT__tba,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__cnts,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__cnt,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__new_set,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__new_cnt,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__cap,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__discrete,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__phase,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__baseband,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__colorphs,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__colormod,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__composite,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__broadcast,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_alu___DOT__add_sub,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_alu___DOT__add_cs,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__run,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__c,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__z,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cond,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__alu_zo,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__wio,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__setphsa,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__setphsb,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__ram_ena,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__plla,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__pllb,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cancel,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__jumpx,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__match,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ctra__DOT__dly,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ctra__DOT__tba,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ctrb__DOT__dly,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ctrb__DOT__tba,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__cnts,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__cnt,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__new_set,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__new_cnt,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__cap,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__discrete,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__phase,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__baseband,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__colorphs,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__colormod,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__composite,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__broadcast,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_alu___DOT__add_sub,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_alu___DOT__add_cs,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__run,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__c,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__z,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cond,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__alu_zo,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__wio,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__setphsa,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__setphsb,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__ram_ena,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__plla,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__pllb,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cancel,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__jumpx,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__match,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ctra__DOT__dly,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ctra__DOT__tba,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ctrb__DOT__dly,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ctrb__DOT__tba,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__cnts,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__cnt,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__new_set,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__new_cnt,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__cap,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__discrete,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__phase,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__baseband,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__colorphs,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__colormod,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__composite,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__broadcast,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_alu___DOT__add_sub,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_alu___DOT__add_cs,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__run,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__c,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__z,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cond,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__alu_zo,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__wio,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__setphsa,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__setphsb,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__ram_ena,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__plla,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__pllb,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cancel,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__jumpx,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__match,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ctra__DOT__dly,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ctra__DOT__tba,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ctrb__DOT__dly,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ctrb__DOT__tba,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__cnts,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__cnt,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__new_set,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__new_cnt,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__cap,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__discrete,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__phase,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__baseband,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__colorphs,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__colormod,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__composite,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__broadcast,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_alu___DOT__add_sub,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_alu___DOT__add_cs,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__run,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__c,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__z,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cond,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__alu_zo,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__wio,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__setphsa,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__setphsb,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__ram_ena,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__plla,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__pllb,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cancel,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__jumpx,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__match,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ctra__DOT__dly,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ctra__DOT__tba,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ctrb__DOT__dly,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ctrb__DOT__tba,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__cnts,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__cnt,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__new_set,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__new_cnt,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__cap,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__discrete,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__phase,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__baseband,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__colorphs,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__colormod,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__composite,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__broadcast,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_alu___DOT__add_sub,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_alu___DOT__add_cs,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__run,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__c,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__z,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cond,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__alu_zo,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__wio,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__setphsa,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__setphsb,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__ram_ena,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__plla,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__pllb,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cancel,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__jumpx,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__match,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ctra__DOT__dly,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ctra__DOT__tba,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ctrb__DOT__dly,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ctrb__DOT__tba,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__cnts,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__cnt,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__new_set,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__new_cnt,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__cap,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__discrete,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__phase,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__baseband,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__colorphs,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__colormod,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__composite,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__broadcast,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_alu___DOT__add_sub,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_alu___DOT__add_cs,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__run,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__c,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__z,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cond,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__alu_zo,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__wio,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__setphsa,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__setphsb,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__ram_ena,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__plla,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__pllb,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cancel,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__jumpx,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__match,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ctra__DOT__dly,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ctra__DOT__tba,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ctrb__DOT__dly,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ctrb__DOT__tba,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__cnts,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__cnt,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__new_set,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__new_cnt,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__cap,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__discrete,7,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__phase,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__baseband,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__colorphs,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__colormod,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__composite,2,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__broadcast,3,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_alu___DOT__add_sub,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_alu___DOT__add_cs,0,0);
    //char	__VpadToAlign348[4];
    VL_SIGW(dig__DOT__bus_a,127,0,4);
    VL_SIG16(dig__DOT__hub___DOT__ac,15,0);
    VL_SIG16(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__px,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__p,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__ram_a,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__set,11,0);
    VL_SIG16(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__px,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__p,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__ram_a,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__set,11,0);
    VL_SIG16(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__px,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__p,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__ram_a,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__set,11,0);
    VL_SIG16(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__px,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__p,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__ram_a,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__set,11,0);
    VL_SIG16(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__px,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__p,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__ram_a,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__set,11,0);
    VL_SIG16(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__px,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__p,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__ram_a,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__set,11,0);
    VL_SIG16(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__px,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__p,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__ram_a,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__set,11,0);
    VL_SIG16(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__px,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__p,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__ram_a,8,0);
    VL_SIG16(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__set,11,0);
    //char	__VpadToAlign434[2];
    VL_SIG(dig__DOT__cnt,31,0);
    VL_SIGW(dig__DOT__bus_d,255,0,8);
    VL_SIG(dig__DOT__bus_q,31,0);
    //char	__VpadToAlign476[4];
    VL_SIGW(dig__DOT__outx,255,0,8);
    VL_SIGW(dig__DOT__dirx,255,0,8);
    VL_SIG(dig__DOT__hub___DOT__dc,31,0);
    VL_SIG(dig__DOT__hub___DOT__mem_d,31,0);
    VL_SIG(dig__DOT__hub___DOT__mem_q,31,0);
    VL_SIG(dig__DOT__hub___DOT__ramq,31,0);
    VL_SIG(dig__DOT__hub___DOT__hub_mem___DOT__rom_q,31,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__ptr,27,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__i,31,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__ram_q,31,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__alu_r,31,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__outa,31,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__dira,31,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__s,31,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__d,31,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__ix,31,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__sy,31,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__sx,31,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ctra__DOT__ctr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ctra__DOT__frq,31,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ctrb__DOT__ctr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ctrb__DOT__frq,31,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__scl,19,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__pixels,31,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__colors,31,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_alu___DOT__dr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_alu___DOT__log_r,31,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_alu___DOT__add_d,31,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_alu___DOT__add_s,31,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__ptr,27,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__i,31,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__ram_q,31,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__alu_r,31,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__outa,31,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__dira,31,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__s,31,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__d,31,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__ix,31,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__sy,31,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__sx,31,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ctra__DOT__ctr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ctra__DOT__frq,31,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ctrb__DOT__ctr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ctrb__DOT__frq,31,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__scl,19,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__pixels,31,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__colors,31,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_alu___DOT__dr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_alu___DOT__log_r,31,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_alu___DOT__add_d,31,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_alu___DOT__add_s,31,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__ptr,27,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__i,31,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__ram_q,31,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__alu_r,31,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__outa,31,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__dira,31,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__s,31,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__d,31,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__ix,31,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__sy,31,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__sx,31,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ctra__DOT__ctr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ctra__DOT__frq,31,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ctrb__DOT__ctr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ctrb__DOT__frq,31,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__scl,19,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__pixels,31,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__colors,31,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_alu___DOT__dr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_alu___DOT__log_r,31,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_alu___DOT__add_d,31,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_alu___DOT__add_s,31,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__ptr,27,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__i,31,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__ram_q,31,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__alu_r,31,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__outa,31,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__dira,31,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__s,31,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__d,31,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__ix,31,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__sy,31,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__sx,31,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ctra__DOT__ctr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ctra__DOT__frq,31,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ctrb__DOT__ctr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ctrb__DOT__frq,31,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__scl,19,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__pixels,31,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__colors,31,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_alu___DOT__dr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_alu___DOT__log_r,31,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_alu___DOT__add_d,31,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_alu___DOT__add_s,31,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__ptr,27,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__i,31,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__ram_q,31,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__alu_r,31,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__outa,31,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__dira,31,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__s,31,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__d,31,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__ix,31,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__sy,31,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__sx,31,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ctra__DOT__ctr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ctra__DOT__frq,31,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ctrb__DOT__ctr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ctrb__DOT__frq,31,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__scl,19,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__pixels,31,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__colors,31,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_alu___DOT__dr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_alu___DOT__log_r,31,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_alu___DOT__add_d,31,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_alu___DOT__add_s,31,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__ptr,27,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__i,31,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__ram_q,31,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__alu_r,31,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__outa,31,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__dira,31,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__s,31,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__d,31,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__ix,31,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__sy,31,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__sx,31,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ctra__DOT__ctr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ctra__DOT__frq,31,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ctrb__DOT__ctr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ctrb__DOT__frq,31,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__scl,19,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__pixels,31,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__colors,31,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_alu___DOT__dr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_alu___DOT__log_r,31,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_alu___DOT__add_d,31,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_alu___DOT__add_s,31,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__ptr,27,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__i,31,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__ram_q,31,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__alu_r,31,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__outa,31,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__dira,31,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__s,31,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__d,31,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__ix,31,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__sy,31,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__sx,31,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ctra__DOT__ctr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ctra__DOT__frq,31,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ctrb__DOT__ctr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ctrb__DOT__frq,31,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__scl,19,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__pixels,31,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__colors,31,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_alu___DOT__dr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_alu___DOT__log_r,31,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_alu___DOT__add_d,31,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_alu___DOT__add_s,31,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__ptr,27,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__i,31,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__ram_q,31,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__alu_r,31,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__outa,31,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__dira,31,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__s,31,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__d,31,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__ix,31,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__sy,31,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__sx,31,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ctra__DOT__ctr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ctra__DOT__frq,31,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ctrb__DOT__ctr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ctrb__DOT__frq,31,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__scl,19,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__pixels,31,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__colors,31,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_alu___DOT__dr,31,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_alu___DOT__log_r,31,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_alu___DOT__add_d,31,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_alu___DOT__add_s,31,0);
    //char	__VpadToAlign1300[4];
    VL_SIG64(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__phsa,32,0);
    VL_SIG64(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__phsb,32,0);
    VL_SIG64(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ctra__DOT__pll_fake,35,0);
    VL_SIG64(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ctrb__DOT__pll_fake,35,0);
    VL_SIG64(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_alu___DOT__rot,62,0);
    VL_SIG64(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_alu___DOT__add_x,34,0);
    VL_SIG64(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__phsa,32,0);
    VL_SIG64(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__phsb,32,0);
    VL_SIG64(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ctra__DOT__pll_fake,35,0);
    VL_SIG64(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ctrb__DOT__pll_fake,35,0);
    VL_SIG64(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_alu___DOT__rot,62,0);
    VL_SIG64(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_alu___DOT__add_x,34,0);
    VL_SIG64(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__phsa,32,0);
    VL_SIG64(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__phsb,32,0);
    VL_SIG64(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ctra__DOT__pll_fake,35,0);
    VL_SIG64(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ctrb__DOT__pll_fake,35,0);
    VL_SIG64(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_alu___DOT__rot,62,0);
    VL_SIG64(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_alu___DOT__add_x,34,0);
    VL_SIG64(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__phsa,32,0);
    VL_SIG64(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__phsb,32,0);
    VL_SIG64(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ctra__DOT__pll_fake,35,0);
    VL_SIG64(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ctrb__DOT__pll_fake,35,0);
    VL_SIG64(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_alu___DOT__rot,62,0);
    VL_SIG64(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_alu___DOT__add_x,34,0);
    VL_SIG64(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__phsa,32,0);
    VL_SIG64(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__phsb,32,0);
    VL_SIG64(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ctra__DOT__pll_fake,35,0);
    VL_SIG64(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ctrb__DOT__pll_fake,35,0);
    VL_SIG64(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_alu___DOT__rot,62,0);
    VL_SIG64(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_alu___DOT__add_x,34,0);
    VL_SIG64(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__phsa,32,0);
    VL_SIG64(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__phsb,32,0);
    VL_SIG64(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ctra__DOT__pll_fake,35,0);
    VL_SIG64(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ctrb__DOT__pll_fake,35,0);
    VL_SIG64(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_alu___DOT__rot,62,0);
    VL_SIG64(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_alu___DOT__add_x,34,0);
    VL_SIG64(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__phsa,32,0);
    VL_SIG64(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__phsb,32,0);
    VL_SIG64(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ctra__DOT__pll_fake,35,0);
    VL_SIG64(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ctrb__DOT__pll_fake,35,0);
    VL_SIG64(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_alu___DOT__rot,62,0);
    VL_SIG64(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_alu___DOT__add_x,34,0);
    VL_SIG64(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__phsa,32,0);
    VL_SIG64(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__phsb,32,0);
    VL_SIG64(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ctra__DOT__pll_fake,35,0);
    VL_SIG64(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ctrb__DOT__pll_fake,35,0);
    VL_SIG64(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_alu___DOT__rot,62,0);
    VL_SIG64(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_alu___DOT__add_x,34,0);
    VL_SIG8(dig__DOT__hub___DOT__hub_mem___DOT__ram3[8192],7,0);
    VL_SIG8(dig__DOT__hub___DOT__hub_mem___DOT__ram2[8192],7,0);
    VL_SIG8(dig__DOT__hub___DOT__hub_mem___DOT__ram1[8192],7,0);
    VL_SIG8(dig__DOT__hub___DOT__hub_mem___DOT__ram0[8192],7,0);
    VL_SIG(dig__DOT__hub___DOT__hub_mem___DOT__rom[8192],31,0);
    VL_SIG(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ram___DOT__r[512],31,0);
    VL_SIG(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ram___DOT__r[512],31,0);
    VL_SIG(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ram___DOT__r[512],31,0);
    VL_SIG(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ram___DOT__r[512],31,0);
    VL_SIG(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ram___DOT__r[512],31,0);
    VL_SIG(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ram___DOT__r[512],31,0);
    VL_SIG(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ram___DOT__r[512],31,0);
    VL_SIG(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ram___DOT__r[512],31,0);
    
    // LOCAL VARIABLES
    // Internals; generally not touched by application code
    static VL_ST_SIG8(__Vtable1_dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__m[128],4,0);
    static VL_ST_SIG8(__Vtable2_dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__m[128],4,0);
    static VL_ST_SIG8(__Vtable3_dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__m[128],4,0);
    static VL_ST_SIG8(__Vtable4_dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__m[128],4,0);
    static VL_ST_SIG8(__Vtable5_dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__m[128],4,0);
    static VL_ST_SIG8(__Vtable6_dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__m[128],4,0);
    static VL_ST_SIG8(__Vtable7_dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__m[128],4,0);
    static VL_ST_SIG8(__Vtable8_dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__m[128],4,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(__Vdly__dig__DOT__hub___DOT__lock_state,7,0);
    VL_SIG8(__Vdlyvset__dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,0,0);
    VL_SIG8(__Vdly__dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vdlyvset__dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,0,0);
    VL_SIG8(__Vdly__dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vdlyvset__dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,0,0);
    VL_SIG8(__Vdly__dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vdlyvset__dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,0,0);
    VL_SIG8(__Vdly__dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vdlyvset__dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,0,0);
    VL_SIG8(__Vdly__dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vdlyvset__dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,0,0);
    VL_SIG8(__Vdly__dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vdlyvset__dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,0,0);
    VL_SIG8(__Vdly__dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vdlyvset__dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,0,0);
    VL_SIG8(__Vdly__dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vdly__dig__DOT__ena_bus,0,0);
    VL_SIG8(__Vdly__dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(__Vdly__dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(__Vdly__dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(__Vdly__dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(__Vdly__dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(__Vdly__dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(__Vdly__dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(__Vdly__dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(__VinpClk__TOP__dig__DOT__coggen__BRA__0__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__VinpClk__TOP__dig__DOT__coggen__BRA__1__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__VinpClk__TOP__dig__DOT__coggen__BRA__2__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__VinpClk__TOP__dig__DOT__coggen__BRA__3__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__VinpClk__TOP__dig__DOT__coggen__BRA__4__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__VinpClk__TOP__dig__DOT__coggen__BRA__5__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__VinpClk__TOP__dig__DOT__coggen__BRA__6__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__VinpClk__TOP__dig__DOT__coggen__BRA__7__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vclklast__TOP__clk_cog,0,0);
    VL_SIG8(__Vclklast__TOP__nres,0,0);
    VL_SIG8(__Vclklast__TOP____VinpClk__TOP__dig__DOT__coggen__BRA__0__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vclklast__TOP____VinpClk__TOP__dig__DOT__coggen__BRA__1__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vclklast__TOP____VinpClk__TOP__dig__DOT__coggen__BRA__2__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vclklast__TOP____VinpClk__TOP__dig__DOT__coggen__BRA__3__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vclklast__TOP____VinpClk__TOP__dig__DOT__coggen__BRA__4__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vclklast__TOP____VinpClk__TOP__dig__DOT__coggen__BRA__5__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vclklast__TOP____VinpClk__TOP__dig__DOT__coggen__BRA__6__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vclklast__TOP____VinpClk__TOP__dig__DOT__coggen__BRA__7__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vclklast__TOP__clk_pll,0,0);
    VL_SIG8(__Vclklast__TOP__dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(__Vclklast__TOP__dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(__Vclklast__TOP__dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(__Vclklast__TOP__dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(__Vclklast__TOP__dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(__Vclklast__TOP__dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(__Vclklast__TOP__dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(__Vclklast__TOP__dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(__Vclklast__TOP__dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(__Vclklast__TOP__dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(__Vclklast__TOP__dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(__Vclklast__TOP__dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(__Vclklast__TOP__dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(__Vclklast__TOP__dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(__Vclklast__TOP__dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(__Vclklast__TOP__dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(__Vchglast__TOP__dig__DOT__coggen__BRA__0__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vchglast__TOP__dig__DOT__coggen__BRA__1__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vchglast__TOP__dig__DOT__coggen__BRA__2__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vchglast__TOP__dig__DOT__coggen__BRA__3__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vchglast__TOP__dig__DOT__coggen__BRA__4__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vchglast__TOP__dig__DOT__coggen__BRA__5__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vchglast__TOP__dig__DOT__coggen__BRA__6__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vchglast__TOP__dig__DOT__coggen__BRA__7__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vchglast__TOP__dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vchglast__TOP__dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vchglast__TOP__dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vchglast__TOP__dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vchglast__TOP__dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vchglast__TOP__dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vchglast__TOP__dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vchglast__TOP__dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    //char	__VpadToAlign83705[1];
    VL_SIG16(__Vdlyvdim0__dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,8,0);
    VL_SIG16(__Vdlyvdim0__dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,8,0);
    VL_SIG16(__Vdlyvdim0__dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,8,0);
    VL_SIG16(__Vdlyvdim0__dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,8,0);
    VL_SIG16(__Vdlyvdim0__dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,8,0);
    VL_SIG16(__Vdlyvdim0__dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,8,0);
    VL_SIG16(__Vdlyvdim0__dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,8,0);
    VL_SIG16(__Vdlyvdim0__dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,8,0);
    //char	__VpadToAlign83722[2];
    VL_SIG(__Vdly__dig__DOT__cnt,31,0);
    VL_SIG(__Vdlyvval__dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,31,0);
    VL_SIG(__Vdlyvval__dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,31,0);
    VL_SIG(__Vdlyvval__dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,31,0);
    VL_SIG(__Vdlyvval__dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,31,0);
    VL_SIG(__Vdlyvval__dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,31,0);
    VL_SIG(__Vdlyvval__dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,31,0);
    VL_SIG(__Vdlyvval__dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,31,0);
    VL_SIG(__Vdlyvval__dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ram___DOT__r__v0,31,0);
    VL_SIG(__Vchglast__TOP__dig__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(__Vchglast__TOP__dig__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(__Vchglast__TOP__dig__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(__Vchglast__TOP__dig__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(__Vchglast__TOP__dig__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(__Vchglast__TOP__dig__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(__Vchglast__TOP__dig__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(__Vchglast__TOP__dig__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIGW(__Vm_traceActivity,127,0,4);
    
    // INTERNAL VARIABLES
    // Internals; generally not touched by application code
    //char	__VpadToAlign83812[4];
    Vdig__Syms*	__VlSymsp;		// Symbol table
    
    // PARAMETERS
    // Parameters marked /*verilator public*/ for use by application code
    
    // CONSTRUCTORS
  private:
    Vdig& operator= (const Vdig&);	///< Copying not allowed
    Vdig(const Vdig&);	///< Copying not allowed
  public:
    /// Construct the model; called by application code
    /// The special name  may be used to make a wrapper with a
    /// single model invisible WRT DPI scope names.
    Vdig(const char* name="TOP");
    /// Destroy the model; called (often implicitly) by application code
    ~Vdig();
    /// Trace signals in the model; called by application code
    void trace (VerilatedVcdC* tfp, int levels, int options=0);
    
    // USER METHODS
    
    // API METHODS
    /// Evaluate the model.  Application must call when inputs change.
    void eval();
    /// Simulation complete, run final blocks.  Application must call on completion.
    void final();
    
    // INTERNAL METHODS
  private:
    static void _eval_initial_loop(Vdig__Syms* __restrict vlSymsp);
  public:
    void __Vconfigure(Vdig__Syms* symsp, bool first);
  private:
    static QData	_change_request(Vdig__Syms* __restrict vlSymsp);
  public:
    static void	_combo__TOP__1(Vdig__Syms* __restrict vlSymsp);
    static void	_combo__TOP__112(Vdig__Syms* __restrict vlSymsp);
    static void	_combo__TOP__47(Vdig__Syms* __restrict vlSymsp);
    static void	_combo__TOP__66(Vdig__Syms* __restrict vlSymsp);
    static void	_combo__TOP__94(Vdig__Syms* __restrict vlSymsp);
  private:
    void	_configure_coverage(Vdig__Syms* __restrict vlSymsp, bool first);
    void	_ctor_var_reset();
  public:
    static void	_eval(Vdig__Syms* __restrict vlSymsp);
    static void	_eval_initial(Vdig__Syms* __restrict vlSymsp);
    static void	_eval_settle(Vdig__Syms* __restrict vlSymsp);
    static void	_initial__TOP__14(Vdig__Syms* __restrict vlSymsp);
    static void	_initial__TOP__84(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__101(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__103(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__105(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__107(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__109(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__18(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__19(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__20(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__21(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__22(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__23(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__24(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__25(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__34(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__37(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__38(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__39(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__40(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__41(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__42(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__43(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__44(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__75(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__77(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__78(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__79(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__80(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__81(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__82(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__83(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__95(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__97(Vdig__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__99(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__10(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__100(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__102(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__104(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__106(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__108(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__11(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__110(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__113(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__114(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__115(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__116(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__117(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__118(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__119(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__12(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__120(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__122(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__123(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__124(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__125(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__126(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__127(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__128(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__129(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__13(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__16(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__17(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__26(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__27(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__28(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__29(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__3(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__30(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__31(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__32(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__33(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__35(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__4(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__45(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__48(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__49(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__5(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__50(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__51(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__52(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__53(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__54(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__55(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__56(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__57(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__58(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__59(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__6(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__60(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__61(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__62(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__63(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__64(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__67(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__68(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__69(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__7(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__70(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__71(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__72(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__73(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__74(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__76(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__8(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__85(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__86(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__87(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__88(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__89(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__9(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__90(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__91(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__92(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__96(Vdig__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__98(Vdig__Syms* __restrict vlSymsp);
    static void	_settle__TOP__111(Vdig__Syms* __restrict vlSymsp);
    static void	_settle__TOP__121(Vdig__Syms* __restrict vlSymsp);
    static void	_settle__TOP__15(Vdig__Syms* __restrict vlSymsp);
    static void	_settle__TOP__36(Vdig__Syms* __restrict vlSymsp);
    static void	_settle__TOP__46(Vdig__Syms* __restrict vlSymsp);
    static void	_settle__TOP__65(Vdig__Syms* __restrict vlSymsp);
    static void	_settle__TOP__93(Vdig__Syms* __restrict vlSymsp);
    static void	traceChgThis(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__10(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__100(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__101(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__102(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__103(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__104(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__105(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__106(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__107(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__108(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__109(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__11(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__110(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__111(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__112(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__113(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__114(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__115(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__116(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__117(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__118(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__119(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__12(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__120(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__121(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__122(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__123(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__124(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__125(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__126(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__127(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__128(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__129(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__13(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__130(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__131(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__132(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__133(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__134(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__135(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__136(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__137(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__138(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__139(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__14(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__140(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__141(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__142(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__143(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__144(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__145(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__146(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__147(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__148(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__149(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__15(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__150(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__151(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__152(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__153(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__154(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__155(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__156(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__157(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__158(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__159(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__16(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__160(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__161(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__162(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__163(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__164(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__165(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__166(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__167(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__168(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__169(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__17(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__170(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__171(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__172(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__173(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__174(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__175(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__176(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__177(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__178(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__179(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__18(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__180(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__181(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__182(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__183(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__184(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__185(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__186(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__187(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__188(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__189(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__19(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__190(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__191(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__192(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__193(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__194(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__195(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__196(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__197(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__198(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__199(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__2(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__20(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__200(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__201(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__202(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__203(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__204(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__205(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__206(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__207(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__208(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__209(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__21(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__210(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__211(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__212(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__213(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__214(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__215(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__216(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__217(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__218(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__219(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__22(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__220(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__221(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__222(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__223(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__224(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__225(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__226(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__227(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__228(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__229(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__23(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__230(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__231(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__232(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__233(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__234(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__235(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__236(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__237(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__238(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__239(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__24(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__240(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__241(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__242(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__243(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__244(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__245(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__246(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__247(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__248(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__249(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__25(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__250(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__251(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__252(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__253(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__254(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__255(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__256(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__257(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__258(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__259(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__26(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__260(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__261(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__262(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__263(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__264(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__265(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__266(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__267(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__268(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__269(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__27(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__270(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__271(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__272(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__28(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__29(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__3(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__30(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__31(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__32(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__33(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__34(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__35(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__36(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__37(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__38(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__39(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__4(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__40(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__41(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__42(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__43(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__44(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__45(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__46(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__47(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__48(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__49(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__5(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__50(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__51(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__52(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__53(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__54(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__55(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__56(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__57(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__58(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__59(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__6(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__60(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__61(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__62(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__63(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__64(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__65(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__66(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__67(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__68(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__69(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__7(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__70(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__71(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__72(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__73(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__74(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__75(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__76(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__77(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__78(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__79(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__8(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__80(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__81(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__82(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__83(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__84(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__85(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__86(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__87(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__88(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__89(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__9(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__90(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__91(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__92(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__93(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__94(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__95(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__96(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__97(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__98(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceChgThis__99(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceFullThis(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceFullThis__1(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceInitThis(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void	traceInitThis__1(Vdig__Syms* __restrict vlSymsp, VerilatedVcd* vcdp, uint32_t code);
    static void traceInit (VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceFull (VerilatedVcd* vcdp, void* userthis, uint32_t code);
    static void traceChg  (VerilatedVcd* vcdp, void* userthis, uint32_t code);
} VL_ATTR_ALIGNED(128);

#endif  /*guard*/
