// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Primary design header
//
// This header should be included by all source files instantiating the design.
// The class here is then constructed to instantiate the design.
// See the Verilator manual for examples.

#ifndef _Vtop_veri_H_
#define _Vtop_veri_H_

#include "verilated.h"
#include "Vtop_veri__Inlines.h"
class Vtop_veri__Syms;

//----------

VL_MODULE(Vtop_veri) {
  public:
    // CELLS
    // Public to allow access to /*verilator_public*/ items;
    // otherwise the application code can consider these internals.
    
    // PORTS
    // The application code writes and reads these signals to
    // propagate new values into/out from the Verilated model.
    VL_IN8(clock,0,0);
    VL_IN8(inp_resn,0,0);
    VL_OUT8(ledg,7,0);
    //char	__VpadToAlign3[1];
    VL_INOUT(io,31,0);
    
    // LOCAL SIGNALS
    // Internals; generally not touched by application code
    VL_SIG8(top_veri__DOT__nres,0,0);
    VL_SIG8(top_veri__DOT__clk_pll,0,0);
    VL_SIG8(top_veri__DOT__clk_cog,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(top_veri__DOT__cfg,7,0);
    VL_SIG8(top_veri__DOT__clkgen__DOT__cfgx,6,0);
    VL_SIG8(top_veri__DOT__clkgen__DOT__clksel,4,0);
    VL_SIG8(top_veri__DOT__core__DOT__ena_bus,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__bus_sel,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__bus_r,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__bus_e,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__bus_w,7,0);
    //char	__VpadToAlign31[1];
    VL_SIG16(top_veri__DOT__core__DOT__bus_s,15,0);
    VL_SIG8(top_veri__DOT__core__DOT__bus_ack,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__pll,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__ptr_w,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__cog_ena,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__rc,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__ec,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__wc,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__sc,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__mem_w,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__mem_wb,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__rd,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__ed,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__sd,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__ad,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__sys_q,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__sys_c,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__cog_e,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__lock_e,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__sys,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__enc,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__num,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__cog_start,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__lock_state,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__hub_mem___DOT__ram_q3,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__hub_mem___DOT__ram_q2,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__hub_mem___DOT__ram_q1,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__hub_mem___DOT__ram_q0,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__hub_mem___DOT__mem,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__run,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__c,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__z,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cond,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__alu_zo,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__wio,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__setphsa,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__setphsb,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__ram_ena,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__plla,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__pllb,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cancel,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__jumpx,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__match,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ctra__DOT__dly,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ctra__DOT__tba,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ctrb__DOT__dly,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ctrb__DOT__tba,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__cnts,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__cnt,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__new_set,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__new_cnt,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__cap,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__discrete,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__phase,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__baseband,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__colorphs,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__colormod,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__composite,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__broadcast,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_alu___DOT__add_sub,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_alu___DOT__add_cs,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__run,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__c,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__z,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cond,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__alu_zo,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__wio,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__setphsa,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__setphsb,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__ram_ena,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__plla,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__pllb,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cancel,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__jumpx,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__match,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ctra__DOT__dly,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ctra__DOT__tba,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ctrb__DOT__dly,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ctrb__DOT__tba,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__cnts,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__cnt,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__new_set,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__new_cnt,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__cap,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__discrete,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__phase,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__baseband,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__colorphs,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__colormod,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__composite,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__broadcast,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_alu___DOT__add_sub,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_alu___DOT__add_cs,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__run,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__c,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__z,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cond,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__alu_zo,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__wio,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__setphsa,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__setphsb,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__ram_ena,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__plla,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__pllb,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cancel,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__jumpx,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__match,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ctra__DOT__dly,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ctra__DOT__tba,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ctrb__DOT__dly,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ctrb__DOT__tba,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__cnts,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__cnt,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__new_set,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__new_cnt,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__cap,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__discrete,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__phase,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__baseband,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__colorphs,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__colormod,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__composite,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__broadcast,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_alu___DOT__add_sub,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_alu___DOT__add_cs,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__run,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__c,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__z,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cond,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__alu_zo,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__wio,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__setphsa,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__setphsb,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__ram_ena,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__plla,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__pllb,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cancel,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__jumpx,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__match,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ctra__DOT__dly,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ctra__DOT__tba,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ctrb__DOT__dly,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ctrb__DOT__tba,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__cnts,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__cnt,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__new_set,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__new_cnt,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__cap,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__discrete,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__phase,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__baseband,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__colorphs,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__colormod,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__composite,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__broadcast,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_alu___DOT__add_sub,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_alu___DOT__add_cs,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__run,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__c,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__z,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cond,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__alu_zo,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__wio,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__setphsa,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__setphsb,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__ram_ena,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__plla,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__pllb,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cancel,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__jumpx,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__match,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ctra__DOT__dly,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ctra__DOT__tba,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ctrb__DOT__dly,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ctrb__DOT__tba,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__cnts,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__cnt,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__new_set,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__new_cnt,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__cap,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__discrete,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__phase,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__baseband,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__colorphs,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__colormod,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__composite,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__broadcast,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_alu___DOT__add_sub,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_alu___DOT__add_cs,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__run,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__c,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__z,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cond,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__alu_zo,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__wio,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__setphsa,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__setphsb,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__ram_ena,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__plla,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__pllb,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cancel,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__jumpx,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__match,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ctra__DOT__dly,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ctra__DOT__tba,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ctrb__DOT__dly,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ctrb__DOT__tba,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__cnts,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__cnt,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__new_set,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__new_cnt,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__cap,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__discrete,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__phase,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__baseband,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__colorphs,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__colormod,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__composite,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__broadcast,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_alu___DOT__add_sub,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_alu___DOT__add_cs,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__run,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__c,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__z,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cond,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__alu_zo,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__wio,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__setphsa,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__setphsb,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__ram_ena,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__plla,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__pllb,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cancel,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__jumpx,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__match,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ctra__DOT__dly,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ctra__DOT__tba,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ctrb__DOT__dly,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ctrb__DOT__tba,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__cnts,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__cnt,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__new_set,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__new_cnt,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__cap,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__discrete,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__phase,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__baseband,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__colorphs,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__colormod,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__composite,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__broadcast,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_alu___DOT__add_sub,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_alu___DOT__add_cs,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__run,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__c,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__z,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cond,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__alu_zo,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__wio,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__setphsa,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__setphsb,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__ram_ena,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__plla,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__pllb,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cancel,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__jumpx,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__match,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ctra__DOT__dly,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ctra__DOT__tba,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ctrb__DOT__dly,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ctrb__DOT__tba,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__cnts,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__cnt,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__new_set,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__new_cnt,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__cap,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__discrete,7,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__phase,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__baseband,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__colorphs,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__colormod,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__composite,2,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__broadcast,3,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_alu___DOT__add_sub,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_alu___DOT__add_cs,0,0);
    VL_SIG16(top_veri__DOT__clkgen__DOT__divide,12,0);
    //char	__VpadToAlign342[2];
    VL_SIGW(top_veri__DOT__core__DOT__bus_a,127,0,4);
    VL_SIG16(top_veri__DOT__core__DOT__hub___DOT__ac,15,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__px,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__p,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__ram_a,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__set,11,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__px,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__p,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__ram_a,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__set,11,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__px,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__p,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__ram_a,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__set,11,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__px,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__p,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__ram_a,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__set,11,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__px,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__p,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__ram_a,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__set,11,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__px,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__p,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__ram_a,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__set,11,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__px,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__p,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__ram_a,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__set,11,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__px,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__p,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__ram_a,8,0);
    VL_SIG16(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__set,11,0);
    //char	__VpadToAlign426[2];
    VL_SIG(top_veri__DOT__pin_out,31,0);
    VL_SIG(top_veri__DOT__pin_dir,31,0);
    VL_SIG(top_veri__DOT__core__DOT__cnt,31,0);
    VL_SIGW(top_veri__DOT__core__DOT__bus_d,255,0,8);
    VL_SIG(top_veri__DOT__core__DOT__bus_q,31,0);
    //char	__VpadToAlign476[4];
    VL_SIGW(top_veri__DOT__core__DOT__outx,255,0,8);
    VL_SIGW(top_veri__DOT__core__DOT__dirx,255,0,8);
    VL_SIG(top_veri__DOT__core__DOT__hub___DOT__dc,31,0);
    VL_SIG(top_veri__DOT__core__DOT__hub___DOT__mem_d,31,0);
    VL_SIG(top_veri__DOT__core__DOT__hub___DOT__mem_q,31,0);
    VL_SIG(top_veri__DOT__core__DOT__hub___DOT__ramq,31,0);
    VL_SIG(top_veri__DOT__core__DOT__hub___DOT__hub_mem___DOT__rom_q,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__ptr,27,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__i,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__ram_q,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__alu_r,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__outa,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__dira,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__s,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__d,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__ix,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__sy,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__sx,31,0);
    VL_SIGW(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ram___DOT__r,16383,0,512);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ctra__DOT__ctr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ctra__DOT__frq,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ctrb__DOT__ctr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ctrb__DOT__frq,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__scl,19,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__pixels,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__colors,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_alu___DOT__dr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_alu___DOT__log_r,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_alu___DOT__add_d,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_alu___DOT__add_s,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__ptr,27,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__i,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__ram_q,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__alu_r,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__outa,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__dira,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__s,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__d,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__ix,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__sy,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__sx,31,0);
    //char	__VpadToAlign2748[4];
    VL_SIGW(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ram___DOT__r,16383,0,512);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ctra__DOT__ctr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ctra__DOT__frq,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ctrb__DOT__ctr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ctrb__DOT__frq,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__scl,19,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__pixels,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__colors,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_alu___DOT__dr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_alu___DOT__log_r,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_alu___DOT__add_d,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_alu___DOT__add_s,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__ptr,27,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__i,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__ram_q,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__alu_r,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__outa,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__dira,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__s,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__d,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__ix,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__sy,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__sx,31,0);
    //char	__VpadToAlign4892[4];
    VL_SIGW(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ram___DOT__r,16383,0,512);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ctra__DOT__ctr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ctra__DOT__frq,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ctrb__DOT__ctr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ctrb__DOT__frq,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__scl,19,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__pixels,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__colors,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_alu___DOT__dr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_alu___DOT__log_r,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_alu___DOT__add_d,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_alu___DOT__add_s,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__ptr,27,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__i,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__ram_q,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__alu_r,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__outa,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__dira,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__s,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__d,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__ix,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__sy,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__sx,31,0);
    //char	__VpadToAlign7036[4];
    VL_SIGW(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ram___DOT__r,16383,0,512);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ctra__DOT__ctr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ctra__DOT__frq,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ctrb__DOT__ctr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ctrb__DOT__frq,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__scl,19,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__pixels,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__colors,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_alu___DOT__dr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_alu___DOT__log_r,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_alu___DOT__add_d,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_alu___DOT__add_s,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__ptr,27,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__i,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__ram_q,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__alu_r,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__outa,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__dira,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__s,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__d,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__ix,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__sy,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__sx,31,0);
    //char	__VpadToAlign9180[4];
    VL_SIGW(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ram___DOT__r,16383,0,512);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ctra__DOT__ctr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ctra__DOT__frq,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ctrb__DOT__ctr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ctrb__DOT__frq,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__scl,19,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__pixels,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__colors,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_alu___DOT__dr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_alu___DOT__log_r,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_alu___DOT__add_d,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_alu___DOT__add_s,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__ptr,27,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__i,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__ram_q,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__alu_r,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__outa,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__dira,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__s,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__d,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__ix,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__sy,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__sx,31,0);
    //char	__VpadToAlign11324[4];
    VL_SIGW(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ram___DOT__r,16383,0,512);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ctra__DOT__ctr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ctra__DOT__frq,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ctrb__DOT__ctr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ctrb__DOT__frq,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__scl,19,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__pixels,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__colors,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_alu___DOT__dr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_alu___DOT__log_r,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_alu___DOT__add_d,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_alu___DOT__add_s,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__ptr,27,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__i,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__ram_q,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__alu_r,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__outa,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__dira,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__s,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__d,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__ix,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__sy,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__sx,31,0);
    //char	__VpadToAlign13468[4];
    VL_SIGW(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ram___DOT__r,16383,0,512);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ctra__DOT__ctr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ctra__DOT__frq,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ctrb__DOT__ctr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ctrb__DOT__frq,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__scl,19,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__pixels,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__colors,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_alu___DOT__dr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_alu___DOT__log_r,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_alu___DOT__add_d,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_alu___DOT__add_s,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__ptr,27,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__i,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__ram_q,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__alu_r,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__outa,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__dira,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__s,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__d,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__ix,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__sy,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__sx,31,0);
    //char	__VpadToAlign15612[4];
    VL_SIGW(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ram___DOT__r,16383,0,512);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ctra__DOT__ctr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ctra__DOT__frq,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ctrb__DOT__ctr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ctrb__DOT__frq,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__scl,19,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__pixels,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__colors,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_alu___DOT__dr,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_alu___DOT__log_r,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_alu___DOT__add_d,31,0);
    VL_SIG(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_alu___DOT__add_s,31,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__phsa,32,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__phsb,32,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ctra__DOT__pll_fake,35,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_ctrb__DOT__pll_fake,35,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_alu___DOT__rot,62,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_alu___DOT__add_x,34,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__phsa,32,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__phsb,32,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ctra__DOT__pll_fake,35,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_ctrb__DOT__pll_fake,35,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_alu___DOT__rot,62,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_alu___DOT__add_x,34,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__phsa,32,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__phsb,32,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ctra__DOT__pll_fake,35,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_ctrb__DOT__pll_fake,35,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_alu___DOT__rot,62,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_alu___DOT__add_x,34,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__phsa,32,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__phsb,32,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ctra__DOT__pll_fake,35,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_ctrb__DOT__pll_fake,35,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_alu___DOT__rot,62,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_alu___DOT__add_x,34,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__phsa,32,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__phsb,32,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ctra__DOT__pll_fake,35,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_ctrb__DOT__pll_fake,35,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_alu___DOT__rot,62,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_alu___DOT__add_x,34,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__phsa,32,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__phsb,32,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ctra__DOT__pll_fake,35,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_ctrb__DOT__pll_fake,35,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_alu___DOT__rot,62,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_alu___DOT__add_x,34,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__phsa,32,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__phsb,32,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ctra__DOT__pll_fake,35,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_ctrb__DOT__pll_fake,35,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_alu___DOT__rot,62,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_alu___DOT__add_x,34,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__phsa,32,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__phsb,32,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ctra__DOT__pll_fake,35,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_ctrb__DOT__pll_fake,35,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_alu___DOT__rot,62,0);
    VL_SIG64(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_alu___DOT__add_x,34,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__hub_mem___DOT__ram3[2048],7,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__hub_mem___DOT__ram2[2048],7,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__hub_mem___DOT__ram1[2048],7,0);
    VL_SIG8(top_veri__DOT__core__DOT__hub___DOT__hub_mem___DOT__ram0[2048],7,0);
    VL_SIG(top_veri__DOT__core__DOT__hub___DOT__hub_mem___DOT__rom[1024],31,0);
    
    // LOCAL VARIABLES
    // Internals; generally not touched by application code
    static VL_ST_SIG8(__Vtable1_top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__m[128],4,0);
    static VL_ST_SIG8(__Vtable2_top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__m[128],4,0);
    static VL_ST_SIG8(__Vtable3_top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__m[128],4,0);
    static VL_ST_SIG8(__Vtable4_top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__m[128],4,0);
    static VL_ST_SIG8(__Vtable5_top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__m[128],4,0);
    static VL_ST_SIG8(__Vtable6_top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__m[128],4,0);
    static VL_ST_SIG8(__Vtable7_top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__m[128],4,0);
    static VL_ST_SIG8(__Vtable8_top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__m[128],4,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(__Vdly__top_veri__DOT__nres,0,0);
    VL_SIG8(__Vdly__top_veri__DOT__core__DOT__hub___DOT__lock_state,7,0);
    VL_SIG8(__Vdly__top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vdly__top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vdly__top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vdly__top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vdly__top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vdly__top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vdly__top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vdly__top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vdly__top_veri__DOT__core__DOT__ena_bus,0,0);
    VL_SIG8(__Vdly__top_veri__DOT__core__DOT__bus_sel,7,0);
    VL_SIG8(__Vdly__top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(__Vdly__top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(__Vdly__top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(__Vdly__top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(__Vdly__top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(__Vdly__top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(__Vdly__top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(__Vdly__top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__m,4,0);
    VL_SIG8(__VinpClk__TOP__top_veri__DOT__nres,0,0);
    VL_SIG8(__VinpClk__TOP__top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__VinpClk__TOP__top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__VinpClk__TOP__top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__VinpClk__TOP__top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__VinpClk__TOP__top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__VinpClk__TOP__top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__VinpClk__TOP__top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__VinpClk__TOP__top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vclklast__TOP__clock,0,0);
    VL_SIG8(__Vclklast__TOP__top_veri__DOT__clk_cog,0,0);
    VL_SIG8(__Vclklast__TOP____VinpClk__TOP__top_veri__DOT__nres,0,0);
    VL_SIG8(__Vclklast__TOP____VinpClk__TOP__top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vclklast__TOP____VinpClk__TOP__top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vclklast__TOP____VinpClk__TOP__top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vclklast__TOP____VinpClk__TOP__top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vclklast__TOP____VinpClk__TOP__top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vclklast__TOP____VinpClk__TOP__top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vclklast__TOP____VinpClk__TOP__top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vclklast__TOP____VinpClk__TOP__top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vclklast__TOP__top_veri__DOT__clk_pll,0,0);
    VL_SIG8(__Vclklast__TOP__top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(__Vclklast__TOP__top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(__Vclklast__TOP__top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(__Vclklast__TOP__top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(__Vclklast__TOP__top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(__Vclklast__TOP__top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(__Vclklast__TOP__top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(__Vclklast__TOP__top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(__Vclklast__TOP__top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(__Vclklast__TOP__top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(__Vclklast__TOP__top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(__Vclklast__TOP__top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(__Vclklast__TOP__top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(__Vclklast__TOP__top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(__Vclklast__TOP__top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT____Vsenitemexpr1,0,0);
    VL_SIG8(__Vclklast__TOP__top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__vclk,0,0);
    VL_SIG8(__Vchglast__TOP__top_veri__DOT__nres,0,0);
    VL_SIG8(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT____Vcellinp__cog___ena,0,0);
    VL_SIG8(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    VL_SIG8(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__snc,1,0);
    //char	__VpadToAlign30478[2];
    VL_SIG(top_veri__DOT__io__out__out0,31,0);
    VL_SIG(top_veri__DOT__io__out__out1,31,0);
    VL_SIG(top_veri__DOT__io__out__out2,31,0);
    VL_SIG(top_veri__DOT__io__out__out3,31,0);
    VL_SIG(top_veri__DOT__io__out__out4,31,0);
    VL_SIG(top_veri__DOT__io__out__out5,31,0);
    VL_SIG(top_veri__DOT__io__out__out6,31,0);
    VL_SIG(top_veri__DOT__io__out__out7,31,0);
    VL_SIG(top_veri__DOT__io__out__out8,31,0);
    VL_SIG(top_veri__DOT__io__out__out9,31,0);
    VL_SIG(top_veri__DOT__io__out__out10,31,0);
    VL_SIG(top_veri__DOT__io__out__out11,31,0);
    VL_SIG(top_veri__DOT__io__out__out12,31,0);
    VL_SIG(top_veri__DOT__io__out__out13,31,0);
    VL_SIG(top_veri__DOT__io__out__out14,31,0);
    VL_SIG(top_veri__DOT__io__out__out15,31,0);
    VL_SIG(top_veri__DOT__io__out__out16,31,0);
    VL_SIG(top_veri__DOT__io__out__out17,31,0);
    VL_SIG(top_veri__DOT__io__out__out18,31,0);
    VL_SIG(top_veri__DOT__io__out__out19,31,0);
    VL_SIG(top_veri__DOT__io__out__out20,31,0);
    VL_SIG(top_veri__DOT__io__out__out21,31,0);
    VL_SIG(top_veri__DOT__io__out__out22,31,0);
    VL_SIG(top_veri__DOT__io__out__out23,31,0);
    VL_SIG(top_veri__DOT__io__out__out24,31,0);
    VL_SIG(top_veri__DOT__io__out__out25,31,0);
    VL_SIG(top_veri__DOT__io__out__out26,31,0);
    VL_SIG(top_veri__DOT__io__out__out27,31,0);
    VL_SIG(top_veri__DOT__io__out__out28,31,0);
    VL_SIG(top_veri__DOT__io__out__out29,31,0);
    VL_SIG(top_veri__DOT__io__out__out30,31,0);
    VL_SIG(top_veri__DOT__io__out__out31,31,0);
    VL_SIG(__Vdly__top_veri__DOT__core__DOT__cnt,31,0);
    VL_SIG(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__0__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__1__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__2__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__3__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__4__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__5__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__6__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    VL_SIG(__Vchglast__TOP__top_veri__DOT__core__DOT__coggen__BRA__7__KET____DOT__cog___DOT__cog_vid___DOT__vid,31,0);
    
    // INTERNAL VARIABLES
    // Internals; generally not touched by application code
    Vtop_veri__Syms*	__VlSymsp;		// Symbol table
    
    // PARAMETERS
    // Parameters marked /*verilator public*/ for use by application code
    
    // CONSTRUCTORS
  private:
    Vtop_veri& operator= (const Vtop_veri&);	///< Copying not allowed
    Vtop_veri(const Vtop_veri&);	///< Copying not allowed
  public:
    /// Construct the model; called by application code
    /// The special name  may be used to make a wrapper with a
    /// single model invisible WRT DPI scope names.
    Vtop_veri(const char* name="TOP");
    /// Destroy the model; called (often implicitly) by application code
    ~Vtop_veri();
    
    // USER METHODS
    
    // API METHODS
    /// Evaluate the model.  Application must call when inputs change.
    void eval();
    /// Simulation complete, run final blocks.  Application must call on completion.
    void final();
    
    // INTERNAL METHODS
  private:
    static void _eval_initial_loop(Vtop_veri__Syms* __restrict vlSymsp);
  public:
    void __Vconfigure(Vtop_veri__Syms* symsp, bool first);
  private:
    static QData	_change_request(Vtop_veri__Syms* __restrict vlSymsp);
  public:
    static void	_combo__TOP__1(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_combo__TOP__114(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_combo__TOP__124(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_combo__TOP__49(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_combo__TOP__5(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_combo__TOP__69(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_combo__TOP__96(Vtop_veri__Syms* __restrict vlSymsp);
  private:
    void	_configure_coverage(Vtop_veri__Syms* __restrict vlSymsp, bool first);
    void	_ctor_var_reset();
  public:
    static void	_eval(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_eval_initial(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_eval_settle(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_initial__TOP__18(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__101(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__103(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__105(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__107(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__109(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__111(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__29(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__31(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__32(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__33(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__34(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__35(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__36(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__37(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__38(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__40(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__41(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__42(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__43(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__44(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__45(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__46(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__47(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__78(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__80(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__81(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__82(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__83(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__84(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__85(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__86(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__97(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_multiclk__TOP__99(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__10(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__100(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__102(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__104(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__106(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__108(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__11(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__110(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__112(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__115(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__116(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__117(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__118(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__119(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__12(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__120(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__121(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__122(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__125(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__126(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__127(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__128(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__129(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__13(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__130(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__131(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__132(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__14(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__15(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__16(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__19(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__20(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__21(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__22(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__23(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__24(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__25(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__26(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__27(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__28(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__3(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__39(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__50(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__51(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__52(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__53(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__54(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__55(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__56(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__57(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__58(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__59(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__6(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__60(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__61(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__62(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__63(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__64(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__65(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__66(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__67(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__7(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__70(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__71(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__72(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__73(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__74(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__75(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__76(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__77(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__79(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__8(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__87(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__88(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__89(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__9(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__90(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__91(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__92(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__93(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__94(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_sequent__TOP__98(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_settle__TOP__113(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_settle__TOP__123(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_settle__TOP__133(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_settle__TOP__17(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_settle__TOP__30(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_settle__TOP__4(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_settle__TOP__48(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_settle__TOP__68(Vtop_veri__Syms* __restrict vlSymsp);
    static void	_settle__TOP__95(Vtop_veri__Syms* __restrict vlSymsp);
} VL_ATTR_ALIGNED(128);

#endif  /*guard*/
