#!/bin/bash

gcc -c eeprom.c 

verilator --trace --top-module top_veri -Wno-lint -O3 --noassert -y ../HDL ../HDL/top_veri.v --cc  --exe main.cpp eeprom.o

cp eeprom.o obj_dir

make -C obj_dir OPT_FAST="-O3" -j -f Vtop_veri.mk Vtop_veri

cp obj_dir/Vtop_veri  simulator

# ./simulator
# gtkwave trace.vcd


