#!/bin/bash

gcc -c eeprom.c 

verilator --trace --top-module dig -Wno-lint -O3 --noassert -y ../HDL ../HDL/dig.v --cc  --exe main.cpp eeprom.o

cp eeprom.o obj_dir

make -C obj_dir OPT_FAST="-O3" -j -f Vdig.mk Vdig

cp obj_dir/Vdig  simulator

# ./simulator
# gtkwave trace.vcd


